name: Publish crates

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  publish_crates:
  name: Build Modified CKB
  runs-on: [ self-hosted, Linux, X64, building ]
  steps:
  - uses: actions/checkout@v2
  - name: Publish crates
    uses: nick-invision/retry@v2
    with:
      timeout_seconds: 7200
      max_attempts: 3
      retry_on: error
      command: |
        cargo login ${{secrets.CRATES_TOKEN}}
        cargo publish
